// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piano.Data;

#nullable disable

namespace Piano.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414174409_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Piano.Models.Docent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Docenten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Daniël Dedden"
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Jan de Boer"
                        });
                });

            modelBuilder.Entity("Piano.Models.Klas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocentId");

                    b.ToTable("Klassen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocentId = 1,
                            Naam = "PianoX1"
                        },
                        new
                        {
                            Id = 2,
                            DocentId = 2,
                            Naam = "PianoX2"
                        });
                });

            modelBuilder.Entity("Piano.Models.Leerling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Niveau")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlasId");

                    b.ToTable("Leerlingen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KlasId = 1,
                            Naam = "Anna Jansen",
                            Niveau = 1
                        },
                        new
                        {
                            Id = 2,
                            KlasId = 1,
                            Naam = "Bram de Vries",
                            Niveau = 2
                        },
                        new
                        {
                            Id = 3,
                            KlasId = 2,
                            Naam = "Sofia Bakker",
                            Niveau = 3
                        });
                });

            modelBuilder.Entity("Piano.Models.Oefening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Oefeningen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Oefening 1",
                            Niveau = 1
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Oefening 2",
                            Niveau = 2
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Oefening 3",
                            Niveau = 3
                        });
                });

            modelBuilder.Entity("Piano.Models.Resultaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeerlingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OefeningId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resultaten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeerlingId = 1,
                            OefeningId = 1,
                            Score = 85,
                            datetime = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            LeerlingId = 2,
                            OefeningId = 2,
                            Score = 92,
                            datetime = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            LeerlingId = 3,
                            OefeningId = 3,
                            Score = 98,
                            datetime = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Piano.Models.Klas", b =>
                {
                    b.HasOne("Piano.Models.Docent", "Docent")
                        .WithMany()
                        .HasForeignKey("DocentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docent");
                });

            modelBuilder.Entity("Piano.Models.Leerling", b =>
                {
                    b.HasOne("Piano.Models.Klas", null)
                        .WithMany("Leerlingen")
                        .HasForeignKey("KlasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Piano.Models.Klas", b =>
                {
                    b.Navigation("Leerlingen");
                });
#pragma warning restore 612, 618
        }
    }
}
