// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piano.Data;

#nullable disable

namespace Piano.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413203544_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Piano.Models.Leerling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Niveau")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Leerlingen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Anna Jansen",
                            Niveau = 1
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Bram de Vries",
                            Niveau = 2
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Sofia Bakker",
                            Niveau = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
